### ISSUE TITLE
[SPIT] Simplifying stock trading using Blockchain

### ISSUE THREAD

**Issue by Meet11** [XinFinOrg/Open-Hackathon#13]
SPIT Hackathon

---

### Crypto Holdings
We aim at providing Blockchain based solution to the
complexities that arise in the Share Market during exchange of
stocks. Primarily, we target at reducing the time taken for a stock
exchange between the end user and the company.
---

### Problem Statement
In general, the time period taken for a complete transaction of
shares takes up to 3 days which we plan on reducing to a couple of
minutes using blockchain technology.
Apart from this, we also plan on making a global platform where
interested investors can invest in global markets without the hassles
involved in registration processes.
---
### Limitations
Although, high scalability of the XDC blockchain, there still lie the 
scaling limitations to our applications as of now due to high number 
of required transactions in a short period of time, which 
would require high rate of verification for transactions.
For the current implementation of our idea/prototype we are 
assuming that the trading is done in a static market 
(Share prices do not change according to real time)
---
### Tech Stack
>Xinfin’s XDC Blockchain : https://github.com/XinFinOrg/XDC01-docker-Nnodes
>Python
---
### Contact Details
Team id : meetgujrathi878
Meet Gujrathi : meetgujrathi@gmail.com
Ritik Poshattiwar : ritik.poshattiwar@gmail.com
Advait Thakur : thakuradvait58@gmail.com

**Comment by punit-agarwal** [comment]
Hello @Meet11 
Thanks for submitting the issue.
Please change the issue title with a sentence that explains your project.
Thanks.

**Comment by punit-agarwal** [comment]
Thanks for changing the title @Meet11
