### ISSUE TITLE
[SPIT] WellCareChain

### ISSUE THREAD

**Issue by jashrathod0** [XinFinOrg/Open-Hackathon#15]
### Project Description*
A Blockchain based solution to address the issue of Patient Data Management in Healthcare. 

### Project Limitations*
The verification depends on the speed of the blockchain consensus. The service can only be used at medical centres and stores that have online facilities. 

### Future Work*
The product can be used by the common man, doctors, hospitals, pathologies and research institutions. It has the potential to transform the healthcare industry. Also, it can also be used for telemedicine communication. The product can be expanded, to allow third parties and developers to make apps and services, built on top of the eco-system. 

### Project Repository*
 [https://github.com/AliabbasMerchant/WellCareChain](url)

### Tech Stack*
XDC Blockchain 
Truffle Suite 
Solidity 
JavaScript and Web3.js 
Bootstrap, HTML, CSS for frontend 
Android for the mobile app 
IPFS for file storage 

### Team Members and Contact info*
Team Code: jashrathod0530

Divy Patel: [divy9881@gmail.com](url)  Github: [https://github.com/DivyPatel9881](url)
Suyash More: [suyash.21.more@gmail.com](url)  Github: [https://github.com/SuyashMore](url)
Aliabbas Merchant: [merchantaliabbas@gmail.com](url)  Github: [https://github.com/AliabbasMerchant](url)

**Comment by SuyashMore** [comment]
# Project Name
WELLCARECHAIN

## Description
A blockchain based solution to address the issue of Patient Data Management in Healthcare.
Right now there is not an efficient & secure system to maintain patient’s
health records.
There is no system which accumulates all the medical records of a person in a
secure manner & gives complete history of a patient’s medical record.

## Functions
The Patient's Data is Stored in Structured Format in his Personal Google Drive which he Grants Access to the Entities Depending upon the Services he Uses.Google Drive is Used for Easy Updation and Fast Access Management.



## Entities
### Patient
    The Following Folder Structure is Present the The Google Drive of the Patient
    1.Doctor Reports
    2.Emergency Info (Available to All Public)
    3.Prescription 
    4.Reports

### Doctor
    The Doctor Provides the QR Code which then is Scanned by the User which grants Read Write Access to the All the Files in the Drive.Again Payment Info is Provided by the Doctor and is Paid in the Same Way through QR Code. 

### Pathologist
    The Pathologist is granted write Access to the "Reports".  

### Chemist
    The Chemist is granted read Access to the "Prescriptions"

Incentivizing the Users by giving importance to the financial value of their Data is Done by Labs and Medical Institutes.

  

## Use case diagram link

<a href="https://ibb.co/71YctSQ"><img src="https://i.ibb.co/LZkwd0r/Capture.png" alt="Capture" border="0"></a>


## Technology stack / technology used ( Very Detailed )

XDC Blockchain
Truffle Suite
Solidity
JavaScript and Web3.js
Bootstrap, HTML, CSS for frontend
Android for the mobile app
Google Drive REST API


## Limitations
The verification depends on the speed of the blockchain consensus.
The service can only be used at medical centres and stores that have online facilities.


## Future Aspects
The product can be used by the common man, doctors, hospitals, pathologies and research institutions.
It has the potential to transform the healthcare industry.
Also, it can also be used for telemedicine communication.
The product can be expanded, to  allow third parties and developers to make apps and services, built on top of the eco-system.
Also It Could be Extended to Provide Insuarance Services.


## github project link

https://github.com/AliabbasMerchant/WellCareChain

## Contact info ( emailid - github id )

Divy Patel: divy9881@gmail.com Github: https://github.com/DivyPatel9881
Suyash More: suyash.21.more@gmail.com Github: https://github.com/SuyashMore
Aliabbas Merchant: merchantaliabbas@gmail.com Github: https://github.com/AliabbasMerchant
