### ISSUE TITLE
[SPIT]-HealthSecure

### ISSUE THREAD

**Issue by lavina98** [XinFinOrg/Open-Hackathon#17]
Project Title*
HealthSecure

Project Description*
Problem Statement: Designing a blockchain system for the health insurance industry to reduce frauds in insurance claims and speed up the entire process of verification of documents 
and claiming money.

Project Limitations:The information provided by the hospitals , health insurance companies should be correct to ensure proper functioning of the system.

Project Repository*
https://github.com/lavina98/HealthSecure

Tech Stack*
● Angular- frontend 
● Go-for blockchain
● Solidity- for smart contracts
● Python for our machine learning code which will be later integrated in Go
● IPFS- to store files
● XDC Blockchain

Team Members and Contact info*
Team ID: luvina1009671
Lavina Golani :luvina1009@gmail.com
Gayatri Nirankar:rmnipankar@gmail.com
Shruti Bengali:bengali.shruti@gmail.com
Varsha Kukreja:varshak333@gmail.com

**Comment by punit-agarwal** [comment]
Hello @lavina98 
Thanks for submitting the issue.
Please change the issue title with a sentence that explains your project.
Thanks.
