### ISSUE TITLE
[SPIT] Certification using Blockchain. 

### ISSUE THREAD

**Issue by HuM4NoiD** [XinFinOrg/Open-Hackathon#32]
### Hackathon Name*
SPIT

---

### Project Title*
certify.me

### Project Description*
This System includes Institutions which will award grades and candidates who will receive grades.
on successful completion of course in an institution, The course completion performance and grades will be appended to the existing chain. The grades and certification can then be requested by the candidate. 

### Project Limitations
Due to append only nature, error prone entries will be very expensive to rectify
Institutions will have to be authenticated as fake certification and grades can be illegitimate organisations registered.

### Project Repository*
https://github.com/HuM4NoiD/certify.me

### Tech Stack*
XDC Blockchain, Javascript, HTML, CSS

### Team Members and Contact info*
Team ID : jugalmistry99541
Jugal Mistry: jugalmistry99@gmail.com
Kaustubh Kekre: kkekre90@gmail.com
Kalpesh Patil: patilkaps99@gmail.com

**Comment by punit-agarwal** [comment]
Hello @HuM4NoiD 
Thanks for submitting the issue.
Please change the issue title with a sentence that explains your project.
Thanks.

**Comment by punit-agarwal** [comment]
Thanks for changing the title.
@HuM4NoiD
