### ISSUE TITLE
SPIT- Proof of Pots

### ISSUE THREAD

**Issue by rikengala** [XinFinOrg/Open-Hackathon#58]
SPIT Hackathon

---

Proof Of Pots

--
Improve Proof of Work (PoW) and Proof of Stake(PoS) Consensus in blockchain:

The disadvantage of Proof of Stake is the ability of owners to monopolize the
network. If they purchase large amount of coins and hold onto to majority of
those coins and dominate the network. Such people can “collude” to carry out
an attack.
Our idea will reduce the power in someone’s hand to validate a block and
instead distribute the power among the group of people having the willingness
to participate in the validation of a given block.
So assume that there is a pool of transactions which are in an unconfirmed
state. A set of transactions will be selected and a conceptual “POT” is formed.

Now the miners that want to participate will lock their respective stakes
irrespective of their amount. There will also be restrictions on the range of
stake amount that could be locked.
Now all the participated people have equal rights of verifying the block
irrespective of the amount their stakes. After reaching a consensus the block
will be verified and added to the chain.
Now the reward that will be earned because of verification will be divided
among the validators participating in the “POT” and their return value depend
upon their comparative percentage of stake locked earlier

-- 
As the reward in Proof of Pots is based on the stake
percentage of the validators, it leads to a case of “Rich
gets richer”.
The energy consumption for all validators is the same
whereas the rewards is based on the stake invested, this
might lead to a case wherein there might not be sufficient
net profit for the low stake validators to incentivise them
to validate.
Initially there will be a dependency on some trusted
validators who have been given the task of adding the
block in the chain. So it’s best used for a closed organisation.

The future scope of our proposed idea can significantly
improve the existing protocols of POS.
The idea can be extended to very large stakes and practically
overcoming the vulnerabilities of PoS and PoW.

The limitations on our statement can be improved significantly by improving the stake handling and participation of every miner for each round.

--
GitHub repository.
https://github.com/rikengala/SPIT-Hackathon-POT

--
HTML,CSS,JS
Flask
Python
Go 

--
Team code - rikengala664

Riken Gala(Team Leader)       rikengala@gmail.com             https://github.com/rikengala
Aadit Kachalia                         aaditkachalia@gmail.com       https://github.com/aaditkachalia
Apurva Dani				apurvadani98@gmail.com	 https://github.com/ApurvaDani
Rohan Kalantri			kalantri.rohan@gmail.com	 https://github.com/rohankalantri

**Comment by riteshkakkad** [comment]
Need detail document on proof of POT flow..
